### ISSUE TITLE
fails to generate

### ISSUE THREAD

**Issue by wanderer** [drom/wast-codegen#1]
codegen crashes with the following

wast
```
(module
  ;; Recursive factorial
  (func (param i64) (result i64)
    (if (i64.eq (get_local 0) (i64.const 0))
      (block
        (i64.const 1)
      )
      (i64.mul (get_local 0) (call 0 (i64.sub (get_local 0) (i64.const 1))))
    )
  )

  (export "fac-rec" 0)
)
```
which after parsed produces

```
{
  "kind": "script",
  "body": [{
    "kind": "module",
    "body": [{
      "kind": "func",
      "type": null,
      "local": [],
      "id": [],
      "param": [{
        "kind": "param",
        "items": [{
          "kind": "item",
          "type": "i64"
        }]
      }],
      "result": {
        "kind": "result",
        "type": "i64"
      },
      "body": [{
        "kind": "if",
        "test": {
          "kind": "relop",
          "type": "i64",
          "operator": "eq",
          "left": {
            "kind": "get_local",
            "id": {
              "kind": "literal",
              "value": 0,
              "raw": "0"
            }
          },
          "right": {
            "kind": "const",
            "type": "i64",
            "init": "0"
          }
        },
        "consequent": {
          "kind": "block",
          "id": null,
          "body": [{
            "kind": "const",
            "type": "i64",
            "init": "1"
          }]
        },
        "alternate": {
          "kind": "binop",
          "type": "i64",
          "operator": "mul",
          "left": {
            "kind": "get_local",
            "id": {
              "kind": "literal",
              "value": 0,
              "raw": "0"
            }
          },
          "right": {
            "kind": "call",
            "id": {
              "kind": "literal",
              "value": 0,
              "raw": "0"
            },
            "expr": [{
              "kind": "binop",
              "type": "i64",
              "operator": "sub",
              "left": {
                "kind": "get_local",
                "id": {
                  "kind": "literal",
                  "value": 0,
                  "raw": "0"
                }
              },
              "right": {
                "kind": "const",
                "type": "i64",
                "init": "1"
              }
            }]
          }
        }
      }]
    }, {
      "kind": "export",
      "name": "fac-rec",
      "id": {
        "kind": "literal",
        "value": 0,
        "raw": "0"
      }
    }]
  }]
}
```

The above json then fails when used
```
 const transformedSrc = codegen.generate(astJSON)
```
with the error

```
/home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:164
            exprGen[node.id.kind](node.id);
                                 ^

TypeError: exprGen[node.id.kind] is not a function
    at Object.exprGen.func (/home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:164:34)
    at Object.exprGen.module (/home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:277:26)
    at /home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:303:28
    at Array.forEach (native)
    at Object.exprGen.script (/home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:302:19)
    at Object.gen [as generate] (/home/null/code/wasm_interface/metering-prototype/node_modules/wast-codegen/lib/index.js:353:23)
    at Object.<anonymous> (/home/null/code/wasm_interface/metering-prototype/index.js:39:32)
    at Module._compile (module.js:417:34)
    at Object.Module._extensions..js (module.js:426:10)
    at Module.load (module.js:357:32)
```

**Comment by drom** [comment]
@wanderer yep, will you take this one?

**Comment by wanderer** [comment]
yep working on it

**Comment by wanderer** [comment]
@drom  so its crashing on ` "id": [ ],` in func. So I kinda think this is wast-parser`s problem. Why is id: []? if there is no id can we just omit it from the json in  wast-parser?

**Comment by drom** [comment]
yep, should be `null` or and `Object`. parser bug
